openapi: 3.0.0
info:
  title: Tshirt store API
  desrciption: create api for ecomm store
  version: 1.1.0
  conatct:
    email: sakshi@google.com
    url: "https://go.in"
# servers:
#   - url: "http://localhost:4000/api/v1"
#     description: for localhost - regular
#   - url: "https://localhost:4000/api/v1"
#     description: for localhost - secure

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for localhost
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer
paths:
  /dummy:
    get:
      tags:
        - Home
      summary: returns a greet message from store
      responses:
        "200":
          description: All good success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
